apiVersion: apps/v1
kind: Deployment
metadata:
  name: orhestrations-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orhestrations
  template:
    metadata:
      labels:
        app: orhestrations
    spec:
      containers:
      - name: orhestrations
        image: shuklaakash/assignment_backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
