apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestration-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestration
  template:
    metadata:
      labels:
        app: orchestration
    spec:
      containers:
      - name: orchestration
        image: shuklaakash/assignment_frontend
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000
